- name: Update apt cache
  hosts: all
  become: yes            # This gives sudo/root access
  gather_facts: no

  tasks:
    - name: Run apt update
      ansible.builtin.apt:
        update_cache: yes


